### ISSUE TITLE
CDN For Tutorial Updates

### ISSUE THREAD

**Issue by pmacMaps** [Esri/esri-leaflet-doc#112]
@jgravois I was planning on updating the **Create your First App** and **Working with Feature Layers** tutorials with the _**1.x Leaflet/2.x Esri-Leaflet**_ set-up.  

What CDN should I use for the Esri plugins?  I saw the Unpkg links don't have the `.js` suffix?  Should I use jsDelivr or something else?

**Comment by jgravois** [comment]
i don't have my heart set on you using a particular CDN, but jsDelivr in particular doesn't have the most up to date esri-leaflet patch releases so i wouldn't recommend using that one.

> I saw the Unpkg links don't have the `.js` suffix?

Yeah, https://unpkg.com is pretty slick.  if no file is specified in a url, it defaults to serving the browser bundle declared in our [`package.json`](https://github.com/Esri/esri-leaflet/blob/20d7d98903e932d3e72af907a4039063f0cc9d0a/package.json#L6).  that said, you're welcome to reference any file from [a release](https://unpkg.com/esri-leaflet@2.0.4/) you want.

is the terseness of not linking explicitly to the built API confusing?

in general, the reason i switched our live samples to use https://unpkg.com because their CDN is fed *directly* from what we publish to [npm's directory](https://www.npmjs.com/package/esri-leaflet) and it was just handy not to have to include an additional step in the release process.
