### ISSUE TITLE
how is esri-leaflet handling the relation between web mercator tiles and lat/lon data?

### ISSUE THREAD

**Issue by joelondon** [Esri/esri-leaflet-doc#171]
hello

given most web tiles are in [web mercator (EPSG:3857)](https://github.com/Esri/esri-leaflet/search?utf8=✓&q=3857&type=) is it a concern that data is handled in [lat/lon (EPSG:4326)](https://github.com/Esri/esri-leaflet/search?utf8=✓&q=4326&type=)

apparently [leaflet resolves lat/lon to web mercator internally](https://gist.github.com/keum/7441007) which should explain why esri-leaflet is handling data as lat/lon - is this along the right lines?

joe

**Comment by jgravois** [comment]
> is it a concern that data is handled in lat/lon (EPSG:4326)

hi @joelondon! i'm not sure exactly how to answer your question!

its a common practice in Leaflet to re-project WGS84 geometries on the client side and display them in Web Mercator applications.

since Esri Leaflet leverages ArcGIS under the hood you can store your actual data in any CRS you want and fetch features from services and re-project them (and even apply datum transformations) to display them in Leaflet.

**Comment by joelondon** [comment]
thanks @jgravois that helps :1st_place_medal:
