### ISSUE TITLE
What is an optional function context?

### ISSUE THREAD

**Issue by ahalota** [Esri/esri-leaflet-doc#175]
I see this throughout the document, such as for the identify task.

I just can't find any explanation of what it is or how to use it!

**Comment by jgravois** [comment]
great question!

we expose an optional function context is to give developers an opportunity to pass through a reference to a variable that they'd like to refer to from _within_ a callback. (typically internally we pass `this` to ensure that it continues to refer to the caller instead of the `Window` || `undefined` )

let me try and come up with an idea for a sample app to include in the documentation site that leverages this feature. in the meantime, one example you could reference occurs inside `tiledMapLayer`

```js
this.metadata(function (error, metadata) {
  // ...
  /* the trailing 'this' is the optional function context
  that assists us in introspecting the instance 
  of tiledMapLayer within this callback
  */
  if (!this.options.attribution && map.attributionControl && metadata.copyrightText) {
    this.options.attribution = metadata.copyrightText;
    map.attributionControl.addAttribution(this.getAttribution());
  }
  // ...
}, this);

```
does that help? either way, i should definitely cover this at Dev Summit this year.

**Comment by gavinr** [comment]
Closing this as I think ^ is a good explanation. Samples around this functionality welcome as PRs!
