### ISSUE TITLE
Unable to Use Webmap on Leaflet

### ISSUE THREAD

**Issue by thefreakingmind12** [Esri/esri-leaflet-doc#181]
I am using the Webmap Library and want to plot a map on Leaflet but I am unable to do so even after copying the webmap id. My Map is not getting on the Map. A Blank Gray area is being shown. Please Fix This Issue.

**Comment by jgravois** [comment]
is your webmap shared publicly? what is its `id`?

**Comment by thefreakingmind12** [comment]
I am Sharing my ID. I am using this first time please help me with it. 76e2cf6139d84ec99d8f7729bbbfe511

**Comment by thefreakingmind12** [comment]
356f60c2ced84b63a29ec0e194e7627a Check this also. Thanks for Help in Advance

**Comment by jgravois** [comment]
our leaflet sample chokes on [`76e2cf6139d84ec99d8f7729bbbfe511`](https://www.arcgis.com/home/webmap/viewer.html?webmap=76e2cf6139d84ec99d8f7729bbbfe511) because the webmap is _not_ shared publicly.

as for [`356f60c2ced84b63a29ec0e194e7627a`](https://www.arcgis.com/home/webmap/viewer.html?webmap=356f60c2ced84b63a29ec0e194e7627a), that webmap _is_ public, but it appears to be corrupt.

![screenshot 2018-06-06 16 07 35](https://user-images.githubusercontent.com/3011734/41069671-cd1fcf7e-69a3-11e8-9524-2798d9735390.png)

**Comment by thefreakingmind12** [comment]
Thank You Very Much. I Made that Public and it worked. One more thing after I implemented it on Leaflet. The Popup showing various information is not showing up on Leaflet but Appearing on The WebMap. How can I implement that popup on Leaflet too.

**Comment by thefreakingmind12** [comment]
Deployed to Heroku.

**Comment by jgravois** [comment]
legends are **not** supported by the webmap [plugin](https://github.com/ynunokawa/L.esri.WebMap).

https://github.com/ynunokawa/L.esri.WebMap/wiki/Supported-Features
