### ISSUE TITLE
Is this repository going away?

### ISSUE THREAD

**Issue by pmacMaps** [Esri/esri-leaflet-doc#325]
I've seen a lot of activity related to moving documentation to https://developers.arcgis.com/esri-leaflet/.  It appears that that site will replace the site powered by this repo.  Is that the case?

And if so, does that mean the community will no longer be able to contribute to the docs for the Esri-Leaflet plugin ecosystem?

**Comment by gavinr** [comment]
@pmacMaps thank you for the question and sorry about the lack of public communication on this topic. These documentation pages are built using "assemble" which is not supported anymore and has more and more security issues as time goes on, so some major action had to happen. Rather than rebuild the site using a different engine (a daunting task), it is better for maintenance overall for the site to live on the ArcGIS Developers site (developers.arcgis.com/esri-leaflet). For community participation, we plan to expose an [issue type](https://github.com/Esri/esri-leaflet/issues/new/choose) of "documentation" in the main esri-leaflet repo to allow the community to report issues and propose changes to the sample code and docs.

**Comment by pmacMaps** [comment]
Thanks for clarifying what's going on.  In the meantime, if there is an example we would like added, what is the best way to submit a request for consideration?

**Comment by gavinr** [comment]
If you want to PR it here, then we'll port it over. Or I'll try to get the issue type in esri-leaflet going soon too.

**Comment by gavinr** [comment]
https://github.com/Esri/esri-leaflet/issues/new?assignees=&labels=Documentation&template=documentation.yml
